# Generated by Django 4.1.5 on 2023-05-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('e_mail', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customer_tb',
            },
        ),
    ]
