# Generated by Django 4.1.5 on 2023-05-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_seller_phone_no'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='Product',
        ),
    ]
