# Generated by Django 4.1.5 on 2023-05-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='username',
            field=models.IntegerField(default=1),
        ),
    ]
