# Generated by Django 4.1.5 on 2023-05-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_seller_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.AddField(
            model_name='seller',
            name='ac_holder_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='seller',
            name='ac_no',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='branch',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='seller',
            name='company_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='e_mail',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='gender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='ifsc',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_no',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='photo',
            field=models.ImageField(default=1, upload_to='seller/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterModelTable(
            name='seller',
            table='seller_tb',
        ),
    ]
