# Generated by Django 4.1.5 on 2023-05-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_username_seller_user_name_remove_seller_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='company_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gender',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_no',
            field=models.BigIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='seller',
            name='photo',
            field=models.ImageField(default='', upload_to='seller/'),
        ),
    ]
